services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DB_PATH=./database.sqlite
    command: "npm start"
